export const FilterOperators = {
  EqualTo: '=',
  NotEqualTo: '!=',
  LessThan: '<',
  LessThanOrEqualTo: '<=',
  GreaterThan: '>',
  GreaterThanOrEqualTo: '>=',
  In: 'IN',
  NotIn: 'NOT IN',
  Is: 'IS',
  IsDistinctFrom: 'IS DISTINCT FROM',
  IsNotDistinctFrom: 'IS NOT DISTINCT FROM',
  Like: 'LIKE',
  ILike: 'ILIKE',
  NotLike: 'NOT LIKE',
  NotILike: 'NOT ILIKE',
  RegExp: '~',
  RegExpCaseInsensitive: '~*',
  NotRegExp: '!~',
  NotRegExpCaseInsensitive: '!~*',
  SimilarTo: 'SIMILAR TO',
  NotSimilarTo: 'NOT SIMILAR TO',
  Contains: 'contains',
  ContainsLeft: '<@',
  ContainsRight: '&&',
  ContainsAny: '&<',
  ContainsAll: '&>',
  Overlaps: '-|-',
  Not: 'NOT',
  Or: 'OR',
  And: 'AND',
  All: 'ALL',
  Any: 'ANY',
  NotAny: 'NOT ANY',
  Between: 'BETWEEN',
  NotBetween: 'NOT BETWEEN',
  IsNull: 'IS NULL',
  NotNull: 'IS NOT NULL',
};
